export const API_ROUTES = {
  login: '/authentication/login/',
  categories: '/categories/admin/category/',
  products: `/ecom/admin/products/`,
  productvariants: `/ecom/admin/product-variants/`,
  variants: `/ecom/admin/product-attributes/`,
  variantValues: `/ecom/admin/product-attribute-values/`,
  orders: '/ecom/admin/orders/',
  specifications: `/ecom/admin/product-specifications/`,
  specificationValues: `/ecom/admin/product-specification-values/`,
  singleOrder: '/ecom/orders/',
  orderStatusChange: '/ecom/orders/{id}/status/',
  salesman: '/mingler/admin/users/salesman/',
  storeManager: '/ecom/admin/store-manager/',
};
