export const API_ROUTES = {
  login: '/authentication/login/',
  categories: '/categories/admin/category/',
  products: `/ecom/admin/products/`,
  productvariants: `/ecom/admin/product-variants/`,
  variants: `/ecom/admin/product-attributes/`,
  variantValues: `/ecom/admin/product-attribute-values/`,
  orders: '/ecom/admin/orders/',
  specifications: `/ecom/admin/product-specifications/`,
  specificationValues: `/ecom/admin/product-specification-values/`,
  singleOrder: '/ecom/admin/orders/',
  orderStatusChange: '/ecom/orders/{id}/status/',
  salesman: '/mingler/admin/users/salesman/',
  storeManager: '/mingler/admin/users/store-manager/',
  serviceStatusChange: '/service/admin/services/{service_id}/',
  services: '/service/admin/services/',
  singleService: 'service/admin/services/{service_id}/',
  serviceStatus :`/service/service-statuses/`,
  deliveryManager: '/authentication/admin/users/',
  promotionList: '/mingler/promotions/',
  promotion: '/mingler/admin/promotions/',
};
