export const API_ROUTES = {
  login: '/authentication/login/',
  categories: '/categories/admin/category/',
  products: `/ecom/admin/products/`,
  productvariants: `/ecom/admin/product-variants/`,
  variants: `/ecom/admin/product-attributes/`,
  variantValues: `/ecom/admin/product-attribute-values/`,
  orders: '/ecom/admin/orders/',
  specifications: `/ecom/admin/product-specifications/`,
  specificationValues: `/ecom/admin/product-specification-values/`,
  singleOrder: '/ecom/admin/orders/',
  orderStatusChange: '/ecom/orders/{id}/status/',
  salesman: '/mingler/admin/users/salesman/',
  storeManager: '/mingler/admin/users/store-manager/',
  serviceStatusChange: '/service/admin/services/{service_id}/',
  // services: '/service/admin/services/',
  services: '/mingler/admin/services/',
  // singleService: 'service/admin/services/{service_id}/',
  singleService: '/mingler/admin/services/{service_id}/',
  serviceStatus: `/service/service-statuses/`,
  deliveryManager: '/authentication/admin/users/',
  promotion: '/mingler/admin/promotions/',
  serviceTypes: '/service/admin/service-types/',
  salesHistory: '/mingler/admin/sales-history/',
  productImages: '/ecom/admin/product-images/',
  suggestions: '/review/',
  stocks: '/mingler/admin/stocks/',
  redeemHistory: '/mingler/admin/redeem-history/',
  redeemApprove: '/mingler/admin/redeem/',
  storePricesByVariant: '/mingler/admin/store-prices/variants/', 
  storePrices: '/mingler/admin/store-prices/',
  dashboard: '/mingler/admin/dashboard/',
  assignDeliveryManager: '/ecom/admin/orders/{id}/assign/',
};
