import { productVariants } from "@/app/shared/ecommerce/product/create-edit/form-utils";

export const routes = {
  eCommerce: {
    dashboard: '/',
    products: '/products',
    createProduct: '/products/create',
    productDetails: (slug: string) => `/products/${slug}`,
    ediProduct: (slug: string) => `/products/${slug}/edit`,
    productVariants: '/products/productvariants',
    productSpecifications: `/specifications`,
    categories: '/categories',
    createCategory: '/categories/create',
    editCategory: (id: string) => `/categories/${id}/edit`,
    serviceDetails: (id: string) => `/servicebooking/${id}/detail`,
    orders: '/orders',
    createOrder: '/orders/create',
    orderDetails: (id: string) => `/orders/${id}`,
    editOrder: (id: string) => `/orders/${id}/edit`,
    reviews: '/reviews',
    servicebooking: '/servicebooking',
    shop: '/shop',
    cart: '/cart',
    promotion: '/promotion',
    promotionDetails: (id: number) => `/promotion/${id}`,
    editPromotion: (id: number) => `/promotion/${id}/edit`,
    checkout: '/checkout',
    trackingId: (id: string) => `/tracking/${id}`,
    storeManager: '/store-manager',
    createStoreManager: '/store-manager/create',
    editStoreManager: (id: number) => `/store-manager/${id}/edit`,

    //sales section
    salesman: '/salesman',
    createSalesman: '/salesman/create',
    editSalesMan: (id: number) => `/salesman/${id}/edit`,
    salesHistory: '/sales-history',
    incentives: '/incentives',
    claimBalanceHistory: '/claim-balance-history',
    deliveryManager: '/delivery-manager',
    createDeliveryManager: '/delivery-manager/create',
    editDeliveryManager: (id: number) => `/delivery-manager/${id}/edit`,
  },
  searchAndFilter: {
    realEstate: '/search/real-estate',
    nft: '/search/nft',
    flight: '/search/flight',
  },
  support: {
    dashboard: '/support',
    inbox: '/support/inbox',
    supportCategory: (category: string) => `/support/inbox/${category}`,
    messageDetails: (id: string) => `/support/inbox/${id}`,
    snippets: '/support/snippets',
    createSnippet: '/support/snippets/create',
    viewSnippet: (id: string) => `/support/snippets/${id}`,
    editSnippet: (id: string) => `/support/snippets/${id}/edit`,
    templates: '/support/templates',
    createTemplate: '/support/templates/create',
    viewTemplate: (id: string) => `/support/templates/${id}`,
    editTemplate: (id: string) => `/support/templates/${id}/edit`,
  },
  logistics: {
    dashboard: '/logistics',
    shipmentList: '/logistics/shipments',
    customerProfile: '/logistics/customer-profile',
    createShipment: '/logistics/shipments/create',
    editShipment: (id: string) => `/logistics/shipments/${id}/edit`,
    shipmentDetails: (id: string) => `/logistics/shipments/${id}`,
    tracking: (id: string) => `/logistics/tracking/${id}`,
  },
  appointment: {
    dashboard: '/appointment',
    appointmentList: '/appointment/list',
  },
  crm: {
    dashboard: '/crm',
  },
  affiliate: {
    dashboard: 'https://isomorphic-dnd.vercel.app',
  },
  storeAnalytics: {
    dashboard: '/store-analytics',
  },
  bidding: {
    dashboard: '/bidding',
  },
  executive: {
    dashboard: '/executive',
  },
  project: {
    dashboard: '/project',
  },
  socialMedia: {
    dashboard: '/social-media',
  },
  jobBoard: {
    dashboard: '/job-board',
    jobFeed: '/job-board/feed',
  },
  analytics: '/analytics',
  financial: {
    dashboard: '/financial',
  },
  podcast: {
    dashboard: '/podcast',
  },
  file: {
    dashboard: '/file',
    manager: '/file-manager',
    upload: '/file-manager/upload',
    create: '/file-manager/create',
  },
  pos: {
    index: '/point-of-sale',
  },
  eventCalendar: '/event-calendar',
  rolesPermissions: '/roles-permissions',
  invoice: {
    home: '/invoice',
    create: '/invoice/create',
    details: (id: string) => `/invoice/${id}`,
    edit: (id: string) => `/invoice/${id}/edit`,
    builder: '/invoice/builder',
  },
  imageViewer: '/image-viewer',
  widgets: {
    cards: '/widgets/cards',
    icons: '/widgets/icons',
    charts: '/widgets/charts',
    maps: '/widgets/maps',
    banners: '/widgets/banners',
  },
  tables: {
    basic: '/tables/basic',
    collapsible: '/tables/collapsible',
    enhanced: '/tables/enhanced',
    pagination: '/tables/pagination',
    search: '/tables/search',
    stickyHeader: '/tables/sticky-header',
    resizable: '/tables/resizable',
    pinning: '/tables/pinning',
    dnd: '/tables/dnd',
  },
  multiStep: '/multi-step',
  multiStep2: '/multi-step-2',
  forms: {
    profileSettings: '/forms/profile-settings',
    notificationPreference: '/forms/profile-settings/notification',
    personalInformation: '/forms/profile-settings/profile',
    newsletter: '/forms/newsletter',
  },
  emailTemplates: '/email-templates',
  profile: '/profile',
  welcome: '/welcome',
  comingSoon: '/coming-soon',
  accessDenied: '/access-denied',
  notFound: '/not-found',
  maintenance: '/maintenance',
  blank: '/blank',
  auth: {
    signUp1: '/auth/sign-up-1',
    signUp2: '/auth/sign-up-2',
    signUp3: '/auth/sign-up-3',
    signUp4: '/auth/sign-up-4',
    signUp5: '/auth/sign-up-5',
    // OTP
    otp1: '/auth/otp-1',
    otp2: '/auth/otp-2',
    otp3: '/auth/otp-3',
    otp4: '/auth/otp-4',
    otp5: '/auth/otp-5',
  },
  signIn: '/signin',
  forgotPassword: '/forgot-password',
};
